default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  host: <%= ENV.fetch("PGHOST", "localhost") %>
  port: <%= ENV.fetch("PGPORT", 5432) %>
  username: <%= ENV["PGUSER"] %>
  password: <%= ENV["PGPASSWORD"] %>

development:
  <<: *default
  database: lewp_reader_development

test:
  <<: *default
  database: lewp_reader_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
