// Typelizer digest 149a6de1958cd893da2a49c9d7334b3c
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from './runtime'
import { buildUrl } from './runtime'

export default {
  /** POST /demo_session */
  create: (options?: RouteOptions): RouteDefinition<'post'> => ({
    url: buildUrl('/demo_session', {}, options),
    method: 'post',
  }),
}
