// Typelizer digest 4922420863c373e0fff79fb6a20a2f25
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from './runtime'
import { buildUrl } from './runtime'

export default {
  /** POST /feeds/:id/refresh */
  refresh: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'post'> => ({
    url: buildUrl('/feeds/:id/refresh', params, options),
    method: 'post',
  }),

  /** PATCH /feeds/:id/mark_all_read */
  markAllRead: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'patch'> => ({
    url: buildUrl('/feeds/:id/mark_all_read', params, options),
    method: 'patch',
  }),

  /** POST /feeds */
  create: (options?: RouteOptions): RouteDefinition<'post'> => ({
    url: buildUrl('/feeds', {}, options),
    method: 'post',
  }),

  /** GET /feeds/:id */
  show: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'get'> => ({
    url: buildUrl('/feeds/:id', params, options),
    method: 'get',
  }),

  /** DELETE /feeds/:id */
  destroy: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'delete'> => ({
    url: buildUrl('/feeds/:id', params, options),
    method: 'delete',
  }),
}
