// Typelizer digest 6813ea2e8832cc9f5aa421c9a2f2c62d
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
export { default as Routes } from './RoutesController'
export { default as dashboard } from './DashboardController'
export { default as demoSessions } from './DemoSessionsController'
export { default as entries } from './EntriesController'
export { default as feeds } from './FeedsController'
export { default as home } from './HomeController'
export { default as identityEmailVerifications } from './Identity/EmailVerificationsController'
export { default as identityPasswordResets } from './Identity/PasswordResetsController'
export { default as reader } from './ReaderController'
export { default as sessions } from './SessionsController'
export { default as settingsEmails } from './Settings/EmailsController'
export { default as settingsPasswords } from './Settings/PasswordsController'
export { default as settingsProfiles } from './Settings/ProfilesController'
export { default as settingsSessions } from './Settings/SessionsController'
export { default as users } from './UsersController'

import _demoSessions from './DemoSessionsController'
import _identityPasswordResets from './Identity/PasswordResetsController'
import _entries from './EntriesController'
import _feeds from './FeedsController'
import _identityEmailVerifications from './Identity/EmailVerificationsController'
import _reader from './ReaderController'
import _home from './HomeController'
import _sessions from './SessionsController'
import _Routes from './RoutesController'
import _settingsEmails from './Settings/EmailsController'
import _settingsPasswords from './Settings/PasswordsController'
import _settingsProfiles from './Settings/ProfilesController'
import _users from './UsersController'

export const demoSession = _demoSessions.create
export const editIdentityPasswordReset = _identityPasswordResets.edit
export const entry = _entries.show
export const feed = _feeds.show
export const identityEmailVerification = _identityEmailVerifications.show
export const identityPasswordReset = _identityPasswordResets.update
export const markAllReadFeed = _feeds.markAllRead
export const markAllReadReader = _reader.markAllRead
export const newIdentityPasswordReset = _identityPasswordResets.new
export const refreshFeed = _feeds.refresh
export const root = _home.index
export const session = _sessions.destroy
export const settingsAppearance = _Routes.settingsAppearance
export const settingsEmail = _settingsEmails.show
export const settingsPassword = _settingsPasswords.show
export const settingsProfile = _settingsProfiles.show
export const signIn = _sessions.new
export const signUp = _users.new
