// Typelizer digest e9b901a8fd4cd2e7d9533527c486118f
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from './runtime'
import { buildUrl } from './runtime'

export default {
  /** PATCH /reader/mark_all_read */
  markAllRead: (options?: RouteOptions): RouteDefinition<'patch'> => ({
    url: buildUrl('/reader/mark_all_read', {}, options),
    method: 'patch',
  }),
}
